# Generated by Django 3.2.17 on 2023-02-10 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='api_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='song',
            name='singer',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='song',
            name='song_name',
            field=models.TextField(default=''),
        ),
    ]
