# Generated by Django 3.2.17 on 2023-02-16 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Message',
            new_name='Profile',
        ),
        migrations.AddField(
            model_name='song',
            name='artistId',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='song',
            name='collectionId',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='song',
            name='singer',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='song',
            name='song_name',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='song',
            name='trackId',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='friendrequest',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
