# Generated by Django 3.2.17 on 2023-02-11 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20230210_1815'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='api_id',
            new_name='artistId',
        ),
        migrations.AddField(
            model_name='song',
            name='collectionId',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='song',
            name='trackId',
            field=models.IntegerField(default=0),
        ),
    ]
